### PR TITLE
Make Windows-friendly

### PR DESCRIPTION
**Pull request by doubleagent**
lein-bikeshed does not run on Windows, but with these small tweaks it does.  Bonus: removes the cli dep.

### CODE REVIEW

**Comment by doubleagent** [comment]
If this is merged then I can also deal with the complaint for pull request #23 ... it's just a simple filter on the files using http://docs.oracle.com/javase/7/docs/api/java/nio/file/FileSystem.html#getPathMatcher(java.lang.String)

**Comment by dakrone** [comment]
Thanks for opening this!

@doubleagent I assume you have a windows machine that this works on? I don't have any windows machines to test on unfortunately

**Comment by doubleagent** [comment]
I ran against lein-bikeshed on Windows 7 & 10, and in Ubuntu on Virtualbox.

**Comment by doubleagent** [comment]
Hm.  Solves Issue #4

**Comment by dakrone** [comment]
Merged, thanks @doubleagent !

**Pull request merged**
